#define TOK_OR                              1
#define TOK_AND                             2
#define TOK_EQ                              3
#define TOK_NEQ                             4
#define TOK_REGEX                           5
#define TOK_NREGEX                          6
#define TOK_NOT                             7
#define TOK_AT                              8
#define TOK_LITERAL                         9
#define TOK_LCURVBR                        10
#define TOK_RCURVBR                        11
#define TOK_LPAREN                         12
#define TOK_RPAREN                         13
#define TOK_CONTAINS                       14
#define TOK_DOLLAR                         15
#define TOK_STRING                         16
#define TOK_LSQBR                          17
#define TOK_RSQBR                          18
#define TOK_EXCL                           19
#define TOK_ANY                            20
#define TOK_BR                             21
#define TOK_NUMBER                         22
#define TOK_SEMICOLON                      23
#define TOK_STAR                           24
